# Generated by Django 2.1.2 on 2018-10-20 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male_number', models.IntegerField()),
                ('female_number', models.IntegerField()),
                ('children_number', models.IntegerField()),
                ('baby_number', models.IntegerField()),
                ('old_number', models.IntegerField()),
                ('disease', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('0', 'want'), ('1', 'want_and_have'), ('2', 'recommend')], max_length=2),
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='api.User'),
        ),
    ]
